{{- if .Values.ingress.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: gateway-{{ .Values.ingress.type }}
      namespace: istio-system
      sectionName: {{ .Values.ingress.scheme }}
  hostnames:
    - grpc-{{ .Values.ingress.hostname }}
  rules:
    - backendRefs:
      - name: {{ .Release.Name }}
        port: {{ .Values.service.grpc.port }}
{{- end -}}