{{- if .Values.ingress.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-dbg
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: gateway-{{ .Values.ingress.type }}
      namespace: istio-system
      sectionName: {{ .Values.ingress.scheme }}
  hostnames:
    - dbg-{{ .Values.ingress.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Release.Name }}
          port: {{ .Values.service.httpDebug.port }}
{{- end -}}