apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Release.Name }}.{{ .Release.Namespace }}.lb.hoolie.io
  gateways:
    - {{ .Release.Name }}-gw
  http:
    - match:
        - port: 80
      route:
        - destination:
            port:
              number: {{ .Values.service.http.port }}
            host: {{ .Release.Name }}
    - match:
        - port: 82
      route:
        - destination:
            port:
              number: {{ .Values.service.grpc.port }}
            host: {{ .Release.Name }}
    - match:
        - port: 84
      route:
        - destination:
            port:
              number: {{ .Values.service.httpDebug.port }}
            host: {{ .Release.Name }}