// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: go_service_template/v1/go-service-template.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoServiceTemplateServiceV1_TestHandler_FullMethodName = "/go_service_template.v1.GoServiceTemplateServiceV1/TestHandler"
)

// GoServiceTemplateServiceV1Client is the client API for GoServiceTemplateServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoServiceTemplateServiceV1Client interface {
	TestHandler(ctx context.Context, in *TestHandlerRequest, opts ...grpc.CallOption) (*TestHandlerResponse, error)
}

type goServiceTemplateServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func NewGoServiceTemplateServiceV1Client(cc grpc.ClientConnInterface) GoServiceTemplateServiceV1Client {
	return &goServiceTemplateServiceV1Client{cc}
}

func (c *goServiceTemplateServiceV1Client) TestHandler(ctx context.Context, in *TestHandlerRequest, opts ...grpc.CallOption) (*TestHandlerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestHandlerResponse)
	err := c.cc.Invoke(ctx, GoServiceTemplateServiceV1_TestHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoServiceTemplateServiceV1Server is the server API for GoServiceTemplateServiceV1 service.
// All implementations should embed UnimplementedGoServiceTemplateServiceV1Server
// for forward compatibility.
type GoServiceTemplateServiceV1Server interface {
	TestHandler(context.Context, *TestHandlerRequest) (*TestHandlerResponse, error)
}

// UnimplementedGoServiceTemplateServiceV1Server should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoServiceTemplateServiceV1Server struct{}

func (UnimplementedGoServiceTemplateServiceV1Server) TestHandler(context.Context, *TestHandlerRequest) (*TestHandlerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestHandler not implemented")
}
func (UnimplementedGoServiceTemplateServiceV1Server) testEmbeddedByValue() {}

// UnsafeGoServiceTemplateServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoServiceTemplateServiceV1Server will
// result in compilation errors.
type UnsafeGoServiceTemplateServiceV1Server interface {
	mustEmbedUnimplementedGoServiceTemplateServiceV1Server()
}

func RegisterGoServiceTemplateServiceV1Server(s grpc.ServiceRegistrar, srv GoServiceTemplateServiceV1Server) {
	// If the following call pancis, it indicates UnimplementedGoServiceTemplateServiceV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoServiceTemplateServiceV1_ServiceDesc, srv)
}

func _GoServiceTemplateServiceV1_TestHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServiceTemplateServiceV1Server).TestHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoServiceTemplateServiceV1_TestHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServiceTemplateServiceV1Server).TestHandler(ctx, req.(*TestHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoServiceTemplateServiceV1_ServiceDesc is the grpc.ServiceDesc for GoServiceTemplateServiceV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoServiceTemplateServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go_service_template.v1.GoServiceTemplateServiceV1",
	HandlerType: (*GoServiceTemplateServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestHandler",
			Handler:    _GoServiceTemplateServiceV1_TestHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go_service_template/v1/go-service-template.proto",
}
