resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

replicas: 1

service:
  http:
    port: 8080
  httpDebug:
    port: 8084
  grpc:
    port: 8082

metrics:
  enabled: true
  port: 8084

ingress:
  enabled: true
  hostname: "dev-go-service-template.hoolie.io"
  type: internal
  scheme: http

env:
  - name: LOG_LEVEL
    value: debug
  - name: ENV
    value: dev